
#config the file manager using toml
#
[manager]
ratio               = [1, 3, 4]
sort_by             = "size"
sort_sensitive      = true
sort_reverse        = false
sort_dir_first      = true
linemode            = "none"
show_hidden         = true
show_symlink        = true
mouse_events        = "click"

[preview]
tab_size = 2
max_width = 900
max_height = 600
cache_dir = ""

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
pdf = [
  { run = 'zathura "$@"', desc = "View PDF", for = 'Unix'},
]


